# -*- coding: utf-8 -*-
"""Langchain_TextSum(DatasetTesting).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17zX2ULu1PlqPU3MwlJIxMQfM77KQEgat
"""

# Required libraries Installation
!pip install langchain langchain_community sumy transformers lexrank datasets rouge rouge_score datasets happytransformer wordcloud
!pip install -U langchain-huggingface
!pip install --upgrade langchain

from langchain.chains import LLMChain
from langchain.llms import HuggingFaceHub
from langchain.prompts import PromptTemplate
from langchain.text_splitter import CharacterTextSplitter
from sumy.summarizers.lex_rank import LexRankSummarizer
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from rouge_score import rouge_scorer
from datasets import load_dataset
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

# Preprocessing: Splitting text using LangChain's CharacterTextSplitter
def preprocess_text(text, chunk_size=7000, chunk_overlap=2500):
    splitter = CharacterTextSplitter(
        separator="\n",
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap
    )
    return splitter.split_text(text)

# Extractive Summarization: LexRank implementation
def extractive_summarization(text, num_sentences=20):
    parser = PlaintextParser.from_string(text, Tokenizer("english"))
    summarizer = LexRankSummarizer()
    summary = summarizer(parser.document, num_sentences)
    return " ".join([str(sentence) for sentence in summary])

# Abstractive Summarization using LangChain (Facebook BART)
prompt = PromptTemplate(
    input_variables=["text"],
    template="Provide a detailed and comprehensive summary of the following text: {text}"
)

# Hugging Face BART (Parameters)
llm = HuggingFaceHub(
    repo_id="facebook/bart-large-cnn",  # Specify the model repository
    task="summarization",
    huggingfacehub_api_token="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",  # Private Hugging Face token (Kamran Mustafa)
    model_kwargs={
        "max_length": 499,  # Max length of the generated summary
        "min_length": 20,   # Min length of the generated summary
        "num_beams": 6,      # beam search
        "length_penalty": 1.0  # Balanced Summary (neither long nor very short)
    }
)

llm_chain = LLMChain(prompt=prompt, llm=llm)

# Abstractive Summarization with LangChain
def abstractive_summarization_langchain(text):
    summary = llm_chain.run({"text": text})
    return summary

# LangChain Pipeline: Combining LexRank and LangChain-based BART summarization
def summarization_pipeline(text, lexrank_sentences=10):
    # Step 1: Extractive Summarization with LexRank
    lexrank_summary = extractive_summarization(text, num_sentences=lexrank_sentences)

    # Step 2: Abstractive Summarization with LangChain (BART)
    bart_summary = abstractive_summarization_langchain(lexrank_summary)
    return bart_summary

# ROUGE Score Calculation
def calculate_rouge(reference, generated):
    scorer = rouge_scorer.RougeScorer(["rouge1", "rouge2", "rougeL"], use_stemmer=True)
    scores = scorer.score(reference, generated)
    return scores

data =[]

# Load CNN/DailyMail dataset (https://huggingface.co/datasets/abisee/cnn_dailymail/viewer/1.0.0/test?row=1)
print("Loading CNN/DailyMail dataset...")
ds = load_dataset("abisee/cnn_dailymail", "3.0.0")
test_data = ds["test"]

# Process top 5 articles
print("\n=== Text Summarization Tool for CNN/DailyMail Dataset ===")
print("Processing top 5 test articles...\n")

for i in range(3):
    article = test_data[i]["article"]
    reference_summary = test_data[i]["highlights"]

    # Preprocess the text
    preprocessed_chunks = preprocess_text(article)
    print(f"\nProcessing article {i + 1}...")

    # Summarize each chunk
    final_summaries = []
    for chunk in preprocessed_chunks:
        summary = summarization_pipeline(chunk)
        final_summaries.append(summary)

    # Combine summaries
    final_summary = " ".join(final_summaries)
    print(f"\nGenerated Summary for Article {i + 1}:\n", final_summary)

    data.append({
        'Original Text': article[:],
        'Reference Summary': reference_summary,
        'Generated Summary': final_summary
    })


    # Calculating ROUGE score
    rouge_scores = calculate_rouge(reference_summary, final_summary)
    print("\nROUGE Scores:")
    for metric, score in rouge_scores.items():
        print(f"{metric.upper()}: Precision: {score.precision:.4f}, Recall: {score.recall:.4f}, F1 Score: {score.fmeasure:.4f}")

import pandas as pd

# Creating a pandas DataFrame from the collected data
df = pd.DataFrame(data)

# print the DataFrame
df

import matplotlib.pyplot as plt

def plot_rouge_scores(rouge_scores):
    metrics = list(rouge_scores.keys())
    precision = [score.precision for score in rouge_scores.values()]
    recall = [score.recall for score in rouge_scores.values()]
    f1 = [score.fmeasure for score in rouge_scores.values()]

    x = range(len(metrics))

    plt.figure(figsize=(10, 6))  # Adjust figure size as needed
    plt.bar(x, precision, width=0.2, label='Precision')
    plt.bar([i + 0.2 for i in x], recall, width=0.2, label='Recall')
    plt.bar([i + 0.4 for i in x], f1, width=0.2, label='F1-Score')

    plt.xlabel("ROUGE Metrics")
    plt.ylabel("Scores")
    plt.title("ROUGE Scores for Summary")
    plt.xticks([i + 0.2 for i in x], metrics)  # Center x-axis labels
    plt.legend()
    plt.tight_layout()
    plt.show()

for i in range(3):
    article = test_data[i]["article"]
    reference_summary = test_data[i]["highlights"]

    # Preprocess the text
    preprocessed_chunks = preprocess_text(article)
    print(f"\nProcessing article {i + 1}...")

    # Summarize each chunk
    final_summaries = []
    for chunk in preprocessed_chunks:
        summary = summarization_pipeline(chunk)
        final_summaries.append(summary)

    # Combine summaries
    final_summary = " ".join(final_summaries)
    print(f"\nGenerated Summary for Article {i + 1}:\n", final_summary)

    # Calculate ROUGE score
    rouge_scores = calculate_rouge(reference_summary, final_summary)
    print("\nROUGE Scores:")
    for metric, score in rouge_scores.items():
        print(f"{metric.upper()}: Precision: {score.precision:.4f}, Recall: {score.recall:.4f}, F1 Score: {score.fmeasure:.4f}")

    # Plot the ROUGE scores
    plot_rouge_scores(rouge_scores)

from wordcloud import WordCloud
import matplotlib.pyplot as plt

def plot_wordcloud(text, ax, title):
    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text)
    ax.imshow(wordcloud, interpolation='bilinear')
    ax.axis("off")
    ax.set_title(title, fontsize=14)

for i in range(3):
    # Using article text, reference summary, and generated summary
    article_text = df['Original Text'][i]
    ref_summary = df["Reference Summary"][i]
    gen_summary = df["Generated Summary"][i]

    # Creating a subplot for each article with 3 columns for the three types of text
    fig, axes = plt.subplots(1, 3, figsize=(18, 6))  # 1 row, 3 columns

    # Word clouds is plotted for the Original Text, Reference Summary, and Generated Summary
    plot_wordcloud(article_text, axes[0], f"Article {i+1} - Original Text")
    print("\n"*2)
    plot_wordcloud(ref_summary, axes[1], f"Article {i+1} - Reference Summary")
    print("\n"*2)
    plot_wordcloud(gen_summary, axes[2], f"Article {i+1} - Generated Summary")

    plt.tight_layout()
    plt.show()

